### ISSUE TITLE
Adjust German Mechanized Tech Tree and Stats

### ISSUE THREAD

**Issue by HjalfnarFeuerwolf** [ULTRA-HOI/HOI4-ULTRA-Project#38]
A while ago I provided Vorondil with the necessary info on how to change the German tech tree order, names and pictures to be more realistic. Sadly he got too busy to implement it, so here I'll drop what I had asked him to do:

rename Sdkfz 250A & Sdkfz 251C ---> Sdkfz 250A & Sdkfz 251B

rename Sdkfz 251D & Sdkfz 250B  ---> Sdkfz 251C & Sdkfz 250B (change picture to new one provided)

rename Kätzchen ---> Sdkfz 251D (and change picture to the mech above)

rename Schützenpanzer Lang ---> Sdkfz 251E (semi-ahistorical, the Czechs kept using the Sdkfz 251D but replaced the wearing out engine with Tatra Diesel engines and later produced them as the OT-810 with an armoured roof welded on top).

add alternative option to Sdkfz 251E named Kätzchen and use picture provided.

![SdKfz-251-AusfC](https://user-images.githubusercontent.com/31015286/179244073-6490515d-a285-4ffe-9e77-971287c15da1.png)
![ot810_sdkfz251E_final2](https://user-images.githubusercontent.com/31015286/179244091-9b766548-c202-4cdc-935f-5951657d1c72.png)
![Kätzchen_final](https://user-images.githubusercontent.com/31015286/179244212-ed67a7cb-a96a-412d-8e05-a8c6c1070ad8.png)

1938 model -> 1939 (first production batch delivered August 39)
1944 model -> 1943
LWS 2 -> 1944
1947 model -> 1946 & give it a 1yr ahead bonus from the Standardpanzer focus

**Comment by myzael** [comment]
What about stats?

**Comment by HjalfnarFeuerwolf** [comment]
Stats are an issue, I'll talk with Shadddo about it and look for quotas for special armament variants.

**Comment by HjalfnarFeuerwolf** [comment]
Alright, further changes necessary:

**Comment by HjalfnarFeuerwolf** [comment]
Done.
